const SSRN_URL = "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6003994";
const DOI = "10.2139/ssrn.6003994";

export const AUTHOR = {
  name: "Martin Erlic",
  path: "/author/martin-erlic",
  ssrnUrl: "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=9773012",
  mediumUrl: "https://medium.com/@SeloSlav",
  xUrl: "https://x.com/seloslav",
} as const;

export const PAPER = {
  title: "Shadow Futures: Contribution Uncertainty and the Self-Reinforcing Market",
  author: AUTHOR.name,
  firstPosted: "December 2025",
  revised: "July 2026",
  publishedDate: "2025-12",
  modifiedDate: "2026-07",
  abstract:
    "Can a market observe productive inputs perfectly and still be unable to learn what those inputs contributed to its rewards? This paper studies adaptive allocation systems in which verified work, effort, measurable quality, cost, foregone income, and capital at risk directly affect reward probabilities, while past reward changes future exposure. I define the market's comparison budget as the cumulative probability mass remaining outside the currently dominant alternative. For a broad class of locally equivalent allocation rules with a common predictable design, finite total comparison makes the complete single-history laws generated by distinct contribution parameters mutually absolutely continuous. No estimator based on one realized market can consistently recover every nonconstant contribution functional, and no test can separate two contribution parameters with vanishing total error. A finite-horizon bound shows that attribution precision is limited by the comparison budget rather than transaction count. Strong reinforcement is a sharp corollary because it exhausts the budget and produces eventual allocation monopoly. With latent position, contribution and position can be exactly observationally equivalent. The unrealized paths needed to separate these explanations are shadow futures. The result does not deny that work or risk matters. It shows that a real causal effect can remain unrecoverable from the path that rewarded it, with implications for platforms, competition policy, entrepreneurship, and merit-sensitive taxation.",
  keywords: [
    "increasing returns",
    "path dependence",
    "identification",
    "cumulative advantage",
    "monopoly",
    "antitrust",
    "taxation",
    "redistribution",
  ],
  jel: ["C13", "C18", "D31", "D43", "D83", "D85", "H21", "L41"],
  doi: DOI,
  doiUrl: `https://doi.org/${DOI}`,
  landingPath: "/paper",
  pdfPath: "/paper.pdf",
  sourcePath: "/paper.docx",
  ssrnUrl: SSRN_URL,
  url: process.env.NEXT_PUBLIC_PAPER_URL ?? SSRN_URL,
  citation:
    'Erlic, Martin. "Shadow Futures: Contribution Uncertainty and the Self-Reinforcing Market." First posted December 2025; revised July 2026. SSRN abstract 6003994. https://doi.org/10.2139/ssrn.6003994.',
  bibtex: `@article{erlic2025shadow,
  title={Shadow Futures: Contribution Uncertainty and the Self-Reinforcing Market},
  author={Erlic, Martin},
  year={2025},
  month={December},
  doi={10.2139/ssrn.6003994},
  url={https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6003994},
  note={Revised July 2026}
}`,
} as const;
