import json
from pathlib import Path

directory = Path(__file__).resolve().parent
description = """Formalize Theorem 1 of Martin Erlic's Shadow Futures: Contribution Uncertainty and the Self-Reinforcing Market (December 2025; revised July 2026): finite comparison-budget impossibility.

Fix n >= 2 recipients and one infinite sequence of recipient observations. Each finite history h has strictly positive normalized probabilities p(beta,h,i). Let w(beta,h) maximize p and epsilon(beta,h) = 1 - p(beta,h,w(beta,h)). Assume squared conditional Hellinger distance between each ordered parameter pair is bounded, at every history, by a finite pair-dependent constant times epsilon under the first parameter. Assume the sum of epsilon along the history is finite almost surely under each parameter's own path law.

Prove: (1) all complete-history laws are mutually absolutely continuous; (2) no finite-prefix estimator consistently recovers any nonconstant real-valued contribution functional at every parameter; (3) no finite-prefix binary tests have both error probabilities tending to zero; (4) no finite-prefix confidence procedure has coverage tending to one at every parameter while its diameter shrinks to zero in probability at every parameter.

The exact proposition fixes the raw terminal sigma-field generated by finite-prefix cylinders and their next-recipient recursion. The sum of squared differences of square roots of the conditional probabilities is the paper's squared Hellinger distance. Ordered-pair bounds cover both directions. The null event of nonsummable residual contestability expresses almost-sure finite budget. All statistical procedures depend only on date and finite prefix.

This is a finite-recipient canonical specialization of Theorem 1, with a common deterministic initial state, strictly positive kernels (stronger than local equivalence), no additional random observations, and real-valued contribution functionals. The paper's argument derives finite accumulated conditional Hellinger separation, applies the filtered-space absolute-continuity criterion, and transfers vanishing event probabilities between equivalent laws.

The economic question is whether real effects of verified work, quality, effort or capital at risk remain recoverable when endogenous allocation exhausts the comparison budget. Equivalence does not mean identical laws or absence of causal effects. Concentration, increasing returns and path dependence alone do not establish the assumptions. Conditional-logit information bounds, strong-reinforcement absorption, finite-horizon rates, latent-position equivalence, empirical applications and policy conclusions are separate obligations.

The preprint already supplies a mathematical argument. This post requests a Lean proof and independent review of the exact statement's correspondence to the paper. It does not claim an existing verified Lean proof or established novelty. See Theorem 1 (pp. 6-7) and Appendix B (pp. 17-19). The proposition and submission draft were prepared with OpenAI Codex.

Additional references: Gabriyelyan, Absolute continuity and singularity of two probability measures on a filtered space, Theorem 1: https://arxiv.org/abs/0802.0385 . Economic and mathematical explanation: https://shadow-futures.vercel.app/math . Preprint DOI: https://doi.org/10.2139/ssrn.6003994 ."""

sources = [
    {
        "title": "Erlic: Shadow Futures - Contribution Uncertainty and the Self-Reinforcing Market",
        "url": "https://shadow-futures.vercel.app/paper.pdf",
        "source_type": "paper",
        "locator": "Theorem 1, pp. 6-7; Appendix B, pp. 17-19; revised July 2026",
        "note": "Primary source for the requested formalization; DOI 10.2139/ssrn.6003994. The paper supplies a mathematical argument, not a verified Lean proof."
    },
    {
        "title": "Gabriyelyan: Absolute continuity and singularity of two probability measures on a filtered space",
        "url": "https://arxiv.org/abs/0802.0385",
        "source_type": "paper",
        "locator": "Theorem 1; discrete-time locally equivalent specialization",
        "note": "Primary mathematical reference underlying the paper's filtered-space Hellinger criterion."
    },
    {
        "title": "Shadow Futures: mathematical model and interactive explanation",
        "url": "https://shadow-futures.vercel.app/math",
        "source_type": "web",
        "locator": "Central implication; interpretation; assumptions",
        "note": "Economic and mathematical context. The website's simulations do not prove the infinite-history claim."
    }
]

problem = {
    "title": "Shadow Futures: finite comparison-budget impossibility",
    "description": description,
    "statement_file": "Statement.lean",
    "profile": "probability",
    "kind": "proof",
    "modules": [],
    "sources": sources,
    "scope": {
        "obligations": ["convergence", "other"],
        "assumptions": [
            "Fixed finite recipient alphabet with n >= 2; raw terminal sigma-field generated by prefix cylinders.",
            "Common deterministic initial state; normalized strictly positive conditional kernels determined by finite prefixes.",
            "The probability laws obey the exact next-recipient cylinder recursion.",
            "Squared Hellinger distance is comparison dominated for every ordered parameter pair and every prefix.",
            "Residual contestability is summable almost surely under every parameter's own path law.",
            "Contribution functionals are real valued and nonconstant; procedures observe only the date and recipient prefix."
        ],
        "cost_metric": "none",
        "model_scope": "Canonical finite-recipient specialization of Theorem 1: equivalent complete-history laws and all four impossibility conclusions, with scalar contribution functionals.",
        "implementation": "Abstract allocation experiment; no empirical dataset or simulator implementation is certified.",
        "correspondence": "abstract_model",
        "limitations": [
            "Strict positivity is stronger than the paper's local-equivalence condition.",
            "The initial state is fixed and no extra parameter-dependent random observations are included.",
            "General metric-valued estimands are outside this target.",
            "No Lean proof is supplied; typechecking establishes statement formation only.",
            "Conditional-logit bounds, strong-reinforcement absorption and finite-horizon rates require separate proofs.",
            "Economic novelty, empirical market classification and policy conclusions are not verification outcomes.",
            "Equivalent laws need not be identical, and productive inputs may still have real causal effects."
        ]
    }
}
draft = {"version": 1, "targets": [{"key": "shadow-futures-impossibility", "problem": problem}]}
(directory / "draft.json").write_text(json.dumps(draft, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
standalone = {**problem, "statement": (directory / "Statement.lean").read_text(encoding="utf-8").strip()}
del standalone["statement_file"]
(directory / "problem.json").write_text(json.dumps(standalone, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("Prepared draft.json and problem.json; statement characters:", len(standalone["statement"]))
